Reenable sbt-unidoc settings (#420)
Copy the UnidocRoot and Unidoc auto plugins from Akka adapted to use
akka-http's .sbt based project build. Exclude akka-parsing due to macros
not supported by sbt-unidoc.

Also fixes an issue with javaunidoc introduced in
bf1631d74ec796f412b9c777bd60e356538d66a3:

    [error] /opt/akka-http/akka-http-core/target/java/akka/http/scaladsl/model/Multipart.java:548: error: illegal start of type
    [error]    *
    [error]    ^
    [error] /opt/akka-http/akka-http-core/target/java/akka/http/scaladsl/model/Multipart.java:549: error: = expected
    [error]    * @deprecated . Since .
    [error]    ^
    [error] /opt/akka-http/akka-http-core/target/java/akka/http/scaladsl/model/Multipart.java:549: error: ';' expected
    [error]    * @deprecated . Since .
    [error]     ^
    [error] /opt/akka-http/akka-http-core/target/java/akka/http/scaladsl/model/Multipart.java:549: error: <identifier> expected
    [error]    * @deprecated . Since .
    [error]                           ^
    [error] /opt/akka-http/akka-http-core/target/java/akka/http/scaladsl/model/Multipart.java:550: error: = expected
    [error]   */
    [error]    ^
    [error] /opt/akka-http/akka-http-core/target/java/akka/http/scaladsl/model/Multipart.java:550: error: ';' expected
    [error]   */
    [error]     ^